services:
  - type: web
    name: eduvision-notes
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
databases:
  - name: postgres
    databaseName: eduvision_notes
    user: postgres